version: "3.7"
services:
  sqlserver:
    # image: mcr.microsoft.com/mssql/server:2019-latest
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    user: root # ubuntu username inside container
    ports:
    #   host-port:container-port 
      - "1433:1433"
    environment:
      # SA_USERNAME: sa
      SA_PASSWORD: Dev1234!
      ACCEPT_EULA: Y
    volumes:
      - ./mssql-data:/var/opt/mssql/data
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db
    ports:  
    #   host-port:container-port
        - "27018:27017"
    environment:
      # I cant get it to work with usee/passwords, so just disable it
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: secret
      PUID: 1000
      PGID: 1000
  postgres:
    image: supabase/postgres:0.14.0 
    user: root # ubuntu username inside container 
    ports:
    #   host-port:container-port 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres # user: postgres
      POSTGRES_PASSWORD: postgres # user: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  mysql:
    image: amd64/mysql:8.0
    ports:
    #   host-port:container-port
      - 3309:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example # user: root
    volumes:
      - ./mysql-data:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    restart: always